apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-sak-frontend
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://barnetrygd.intern.dev.nav.no
    - https://barnetrygd.ansatt.dev.nav.no
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - https://barnetrygd.ansatt.dev.nav.no/auth/openid/callback
      claims:
        groups:
          - id: "93a26831-9866-4410-927b-74ff51a9107c"  # VEILEDER_ROLLE
          - id: "d21e00a4-969d-4b28-8782-dc818abfae65"  # SAKSBEHANDLER_ROLLE
          - id: "9449c153-5a1e-44a7-84c6-7cc7a8867233"  # BESLUTTER_ROLLE
          - id: "314fa714-f13c-4cdc-ac5c-e13ce08e241c"  # SUPERBRUKER_ROLLE
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: familie-ba-sak
        - application: familie-endringslogg
  envFrom:
    - secret: ba-sak-frontend
  env:
    - name: APP_VERSION
      value: {{ VERSION }}
    - name: GITHUB_BRANCH
      value: { { GITHUB_BRANCH } }
    - name: ENV
      value: preprod
  redis:
    - instance: sessions
      access: readwrite
    - instance: lookup
      access: read
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs