apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-sak-frontend
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  istio:
    enabled: false
  ingresses:
    - https://barnetrygd.dev.adeo.no
  vault:
    enabled: true
  webproxy: true
  env:
    - name: APP_VERSION
      value: {{ VERSION }}
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "93a26831-9866-4410-927b-74ff51a9107c"  # VEILEDER_ROLLE
          - id: "d21e00a4-969d-4b28-8782-dc818abfae65"  # SAKSBEHANDLER_ROLLE
          - id: "9449c153-5a1e-44a7-84c6-7cc7a8867233"  # BESLUTTER_ROLLE
  accessPolicy:
    outbound:
      rules:
        - application: familie-ba-sak

