import { VedtakBegrunnelse } from '../../typer/vedtak';

export const sanityBegrunnelseTilApiNavnDictionary: Record<VedtakBegrunnelse, string> = {
    [VedtakBegrunnelse.INNVILGET_BOSATT_I_RIKTET]: 'norskNordiskBosattINorge',
    [VedtakBegrunnelse.INNVILGET_BOSATT_I_RIKTET_LOVLIG_OPPHOLD]: 'tredjelandsborgerMedLovligOpph',
    [VedtakBegrunnelse.INNVILGET_LOVLIG_OPPHOLD_OPPHOLDSTILLATELSE]:
        'tredjelandsborgerBosattForLovl',
    [VedtakBegrunnelse.INNVILGET_LOVLIG_OPPHOLD_EØS_BORGER]: 'eosborgerSokerHarOppholdsrett',
    [VedtakBegrunnelse.INNVILGET_LOVLIG_OPPHOLD_EØS_BORGER_SKJØNNSMESSIG_VURDERING]:
        'eosborgerSkjonnsmessigVurderin',
    [VedtakBegrunnelse.INNVILGET_OMSORG_FOR_BARN]: 'adopsjonSurrogatiOmsorgenForBarn',
    [VedtakBegrunnelse.INNVILGET_BOR_HOS_SØKER]: 'barnHarFlyttetTilSokerFlytting',
    [VedtakBegrunnelse.INNVILGET_NYFØDT_BARN_FØRSTE]: 'nyfodtBarnForsteBarn',
    [VedtakBegrunnelse.INNVILGET_NYFØDT_BARN]: 'adopsjonSurrogatiOmsorgenForBa',
    [VedtakBegrunnelse.INNVILGET_FAST_OMSORG_FOR_BARN]: 'nyfodtBarnHarBarnFraFor',

    // Under finnes ikke i Sanity enda
    [VedtakBegrunnelse.INNVILGET_FØDSELSHENDELSE_NYFØDT_BARN]: '',
    [VedtakBegrunnelse.INNVILGET_FØDSELSHENDELSE_NYFØDT_BARN_FØRSTE]: '',
    [VedtakBegrunnelse.REDUKSJON_BOSATT_I_RIKTET]: 'REDUKSJON_BOSATT_I_RIKTET',
    [VedtakBegrunnelse.REDUKSJON_LOVLIG_OPPHOLD_OPPHOLDSTILLATELSE_BARN]:
        'REDUKSJON_LOVLIG_OPPHOLD_OPPHOLDSTILLATELSE_BARN',
    [VedtakBegrunnelse.REDUKSJON_FLYTTET_FORELDER]: 'REDUKSJON_FLYTTET_FORELDER',
    [VedtakBegrunnelse.REDUKSJON_FLYTTET_BARN]: 'REDUKSJON_FLYTTET_BARN',
    [VedtakBegrunnelse.REDUKSJON_BARN_DØD]: 'REDUKSJON_BARN_DØD',
    [VedtakBegrunnelse.REDUKSJON_FAST_OMSORG_FOR_BARN]: 'REDUKSJON_FAST_OMSORG_FOR_BARN',
    [VedtakBegrunnelse.REDUKSJON_MANGLENDE_OPPLYSNINGER]: 'REDUKSJON_MANGLENDE_OPPLYSNINGER',
    [VedtakBegrunnelse.REDUKSJON_UNDER_18_ÅR]: 'REDUKSJON_UNDER_18_ÅR',
    [VedtakBegrunnelse.REDUKSJON_UNDER_6_ÅR]: 'REDUKSJON_UNDER_6_ÅR',
    [VedtakBegrunnelse.REDUKSJON_DELT_BOSTED_ENIGHET]: 'REDUKSJON_DELT_BOSTED_ENIGHET',
    [VedtakBegrunnelse.REDUKSJON_DELT_BOSTED_UENIGHET]: 'REDUKSJON_DELT_BOSTED_UENIGHET',
    [VedtakBegrunnelse.REDUKSJON_ENDRET_MOTTAKER]: 'REDUKSJON_ENDRET_MOTTAKER',
    [VedtakBegrunnelse.REDUKSJON_FRITEKST]: 'REDUKSJON_FRITEKST',
    [VedtakBegrunnelse.INNVILGET_SATSENDRING]: 'INNVILGET_SATSENDRING',
    [VedtakBegrunnelse.OPPHØR_BARN_FLYTTET_FRA_SØKER]: 'OPPHØR_BARN_FLYTTET_FRA_SØKER',
    [VedtakBegrunnelse.OPPHØR_SØKER_FLYTTET_FRA_BARN]: 'OPPHØR_SØKER_FLYTTET_FRA_BARN',
    [VedtakBegrunnelse.OPPHØR_SØKER_UTVANDRET]: 'OPPHØR_SØKER_UTVANDRET',
    [VedtakBegrunnelse.OPPHØR_BARN_DØD]: 'OPPHØR_BARN_DØD',
    [VedtakBegrunnelse.OPPHØR_SØKER_HAR_IKKE_FAST_OMSORG]: 'OPPHØR_SØKER_HAR_IKKE_FAST_OMSORG',
    [VedtakBegrunnelse.OPPHØR_BARN_HAR_IKKE_OPPHOLDSTILLATELSE]:
        'OPPHØR_BARN_HAR_IKKE_OPPHOLDSTILLATELSE',
    [VedtakBegrunnelse.OPPHØR_SØKER_HAR_IKKE_OPPHOLDSTILLATELSE]:
        'OPPHØR_SØKER_HAR_IKKE_OPPHOLDSTILLATELSE',
    [VedtakBegrunnelse.OPPHØR_DELT_BOSTED_OPPHØRT_ENIGHET]: 'OPPHØR_DELT_BOSTED_OPPHØRT_ENIGHET',
    [VedtakBegrunnelse.OPPHØR_DELT_BOSTED_OPPHØRT_UENIGHET]: 'OPPHØR_DELT_BOSTED_OPPHØRT_UENIGHET',
    [VedtakBegrunnelse.OPPHØR_ENDRET_MOTTAKER]: 'OPPHØR_ENDRET_MOTTAKER',
    [VedtakBegrunnelse.OPPHØR_UNDER_18_ÅR]: 'OPPHØR_UNDER_18_ÅR',
    [VedtakBegrunnelse.OPPHØR_FRITEKST]: 'OPPHØR_FRITEKST',
    [VedtakBegrunnelse.OPPHØR_IKKE_MOTTATT_OPPLYSNINGER]: 'OPPHØR_IKKE_MOTTATT_OPPLYSNINGER',
    [VedtakBegrunnelse.AVSLAG_BOSATT_I_RIKET]: 'AVSLAG_BOSATT_I_RIKET',
    [VedtakBegrunnelse.AVSLAG_LOVLIG_OPPHOLD_TREDJELANDSBORGER]:
        'AVSLAG_LOVLIG_OPPHOLD_TREDJELANDSBORGER',
    [VedtakBegrunnelse.AVSLAG_BOR_HOS_SØKER]: 'AVSLAG_BOR_HOS_SØKER',
    [VedtakBegrunnelse.AVSLAG_OMSORG_FOR_BARN]: 'AVSLAG_OMSORG_FOR_BARN',
    [VedtakBegrunnelse.AVSLAG_LOVLIG_OPPHOLD_EØS_BORGER]: 'AVSLAG_LOVLIG_OPPHOLD_EØS_BORGER',
    [VedtakBegrunnelse.AVSLAG_LOVLIG_OPPHOLD_SKJØNNSMESSIG_VURDERING_TREDJELANDSBORGER]:
        'AVSLAG_LOVLIG_OPPHOLD_SKJØNNSMESSIG_VURDERING_TREDJELANDSBORGER',
    [VedtakBegrunnelse.AVSLAG_MEDLEM_I_FOLKETRYGDEN]: 'AVSLAG_MEDLEM_I_FOLKETRYGDEN',
    [VedtakBegrunnelse.AVSLAG_FORELDRENE_BOR_SAMMEN]: 'AVSLAG_FORELDRENE_BOR_SAMMEN',
    [VedtakBegrunnelse.AVSLAG_UNDER_18_ÅR]: 'AVSLAG_UNDER_18_ÅR',
    [VedtakBegrunnelse.AVSLAG_UGYLDIG_AVTALE_OM_DELT_BOSTED]:
        'AVSLAG_UGYLDIG_AVTALE_OM_DELT_BOSTED',
    [VedtakBegrunnelse.AVSLAG_IKKE_AVTALE_OM_DELT_BOSTED]: 'AVSLAG_IKKE_AVTALE_OM_DELT_BOSTED',
    [VedtakBegrunnelse.AVSLAG_OPPLYSNINGSPLIKT]: 'AVSLAG_OPPLYSNINGSPLIKT',
    [VedtakBegrunnelse.AVSLAG_SÆRKULLSBARN]: 'AVSLAG_OPPLYSNINGSPLIKT',
    [VedtakBegrunnelse.AVSLAG_FRITEKST]: 'AVSLAG_FRITEKST',
    [VedtakBegrunnelse.FORTSATT_INNVILGET_SØKER_OG_BARN_BOSATT_I_RIKET]:
        'FORTSATT_INNVILGET_SØKER_OG_BARN_BOSATT_I_RIKET',
    [VedtakBegrunnelse.FORTSATT_INNVILGET_SØKER_BOSATT_I_RIKET]:
        'FORTSATT_INNVILGET_SØKER_BOSATT_I_RIKET',
    [VedtakBegrunnelse.FORTSATT_INNVILGET_BARN_BOSATT_I_RIKET]:
        'FORTSATT_INNVILGET_BARN_BOSATT_I_RIKET',
    [VedtakBegrunnelse.FORTSATT_INNVILGET_BARN_OG_SØKER_LOVLIG_OPPHOLD_OPPHOLDSTILLATELSE]:
        'FORTSATT_INNVILGET_BARN_OG_SØKER_LOVLIG_OPPHOLD_OPPHOLDSTILLATELSE',
    [VedtakBegrunnelse.FORTSATT_INNVILGET_SØKER_LOVLIG_OPPHOLD_OPPHOLDSTILLATELSE]:
        'FORTSATT_INNVILGET_SØKER_LOVLIG_OPPHOLD_OPPHOLDSTILLATELSE',
    [VedtakBegrunnelse.FORTSATT_INNVILGET_BARN_LOVLIG_OPPHOLD_OPPHOLDSTILLATELSE]:
        'FORTSATT_INNVILGET_BARN_LOVLIG_OPPHOLD_OPPHOLDSTILLATELSE',
    [VedtakBegrunnelse.FORTSATT_INNVILGET_BOR_MED_SØKER]: 'FORTSATT_INNVILGET_BOR_MED_SØKER',
    [VedtakBegrunnelse.FORTSATT_INNVILGET_FAST_OMSORG]: 'FORTSATT_INNVILGET_FAST_OMSORG',
    [VedtakBegrunnelse.FORTSATT_INNVILGET_LOVLIG_OPPHOLD_EØS]:
        'FORTSATT_INNVILGET_LOVLIG_OPPHOLD_EØS',
    [VedtakBegrunnelse.FORTSATT_INNVILGET_LOVLIG_OPPHOLD_TREDJELANDSBORGER]:
        'FORTSATT_INNVILGET_LOVLIG_OPPHOLD_TREDJELANDSBORGER',
    [VedtakBegrunnelse.FORTSATT_INNVILGET_FRITEKST]: 'FORTSATT_INNVILGET_FRITEKST',
};

export const sanityApiNavnTilBegrunnelseDictionary: Record<
    string,
    VedtakBegrunnelse
> = Object.fromEntries(
    new Map<string, VedtakBegrunnelse>(
        Object.entries(sanityBegrunnelseTilApiNavnDictionary).map(([key, value]) => [
            value,
            key,
        ]) as [string, VedtakBegrunnelse][]
    )
);
