import type { Resultat } from './vilkår';
export interface IFødselshendelsefiltreringResultat {
    filtreringsregel: Filtreringsregel;
    resultat: Resultat;
    begrunnelse: string;
}
export declare enum Filtreringsregel {
    MOR_GYLDIG_FNR = "MOR_GYLDIG_FNR",
    BARN_GYLDIG_FNR = "BARN_GYLDIG_FNR",
    MOR_LEVER = "MOR_LEVER",
    BARN_LEVER = "BARN_LEVER",
    MER_ENN_5_MND_SIDEN_FORRIGE_BARN = "MER_ENN_5_MND_SIDEN_FORRIGE_BARN",
    MOR_ER_OVER_18_ÅR = "MOR_ER_OVER_18_\u00C5R",
    MOR_HAR_IKKE_VERGE = "MOR_HAR_IKKE_VERGE",
    MOR_MOTTAR_IKKE_LØPENDE_UTVIDET = "MOR_MOTTAR_IKKE_L\u00D8PENDE_UTVIDET",
    MOR_HAR_IKKE_LØPENDE_EØS_BARNETRYGD = "MOR_HAR_IKKE_L\u00D8PENDE_E\u00D8S_BARNETRYGD",
    LØPER_IKKE_BARNETRYGD_FOR_BARNET = "L\u00D8PER_IKKE_BARNETRYGD_FOR_BARNET",
    FAGSAK_IKKE_MIGRERT_UT_AV_INFOTRYGD_ETTER_BARN_FØDT = "FAGSAK_IKKE_MIGRERT_UT_AV_INFOTRYGD_ETTER_BARN_F\u00D8DT",
    MOR_HAR_IKKE_OPPFYLT_UTVIDET_VILKÅR_VED_FØDSELSDATO = "MOR_HAR_IKKE_OPPFYLT_UTVIDET_VILK\u00C5R_VED_F\u00D8DSELSDATO",
    MOR_HAR_IKKE_OPPHØRT_BARNETRYGD = "MOR_HAR_IKKE_OPPH\u00D8RT_BARNETRYGD"
}
export declare const filtreringsregler: Record<Filtreringsregel, string>;
