name: Build&deploy to dev-gcp

on:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/navikt/familie-ba-sak-frontend:${{ github.sha }}
  VERSION: familie-ba-sak-frontend:${{ github.sha }}


jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/yarn-cache
      - name: Yarn install
        run: yarn --prefer-offline --frozen-lockfile
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_RELEASE: ${{ github.sha }}
        run: |
          yarn build
          yarn test
          yarn run cypress
          docker build . -t ${IMAGE}
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker push ${IMAGE}
  deploy:
    name: Deploy to dev-gcp team namespace
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: build_n_deploy/naiserator/gcp-dev.yaml
          VAR: VERSION=${{ env.VERSION }}
