# Full pipeline on push to main. Build, test, and deploy to dev + prod
name: Main
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.github/*.yaml'
      - '.gitignore'
      - '.prettierignore'
      - '.prettierrc'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'eslint.config.mjs'

jobs:
  build:
    name: Build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/familie-baks-gha-workflows/.github/workflows/build-yarn-app.yaml@main
    with:
      build-image: true
      push-image: true
      skip-cypress: false
    secrets: inherit
  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
    needs: [ build ]
    uses: navikt/familie-baks-gha-workflows/.github/workflows/deploy.yaml@main
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: dev-gcp
      resource: .nais/app-dev.yaml
    secrets: inherit
  deploy-prod:
    name: Deploy prod
    permissions:
      id-token: write
    needs: [ build, deploy-dev ]
    uses: navikt/familie-baks-gha-workflows/.github/workflows/deploy.yaml@main
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: prod-gcp
      resource: .nais/app-prod.yaml
    secrets: inherit
