name: Manual deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - dev
          - prod
      skip-tests:
        description: 'Skip tests?'
        default: false
        type: boolean
      skip-validation:
        description: 'Skip validation? (eslint, prettier, typecheck)'
        default: false
        type: boolean
      skip-cypress:
        description: 'Skip cypress?'
        default: false
        type: boolean

jobs:
  build:
    name: Build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/familie-baks-gha-workflows/.github/workflows/build-yarn-app.yaml@main
    with:
      build-image: true
      push-image: true
      skip-tests: ${{ inputs.skip-tests }}
      skip-validation: ${{ inputs.skip-validation }}
      skip-cypress: ${{ inputs.skip-cypress }}
    secrets: inherit
  deploy-with-new-image:
    name: Deploy with new image
    permissions:
      id-token: write
    needs: [ build ]
    uses: navikt/familie-baks-gha-workflows/.github/workflows/deploy.yaml@main
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: ${{ inputs.environment }}-gcp
      resource: .nais/app-${{ inputs.environment }}.yaml
    secrets: inherit
