name: Pull request
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: Pull request
    permissions:
      contents: read
    uses: navikt/familie-baks-gha-workflows/.github/workflows/pull-request-pnpm.yaml@main # ratchet:exclude
    with:
      node-version: '24'
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  playwright:
    name: Playwright
    if: github.actor != 'team-baks-digestabot[bot]'
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TZ: 'Europe/Oslo'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # ratchet:step-security/harden-runner@v2.20.1
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: Set up node and install pnpm packages
        uses: navikt/familie-baks-gha-workflows/.github/actions/setup-node-pnpm@main # ratchet:exclude
        with:
          node-version: '24'
          reader-token: ${{ secrets.READER_TOKEN }}
      - name: Install Playwright browser
        run: pnpm exec playwright install --with-deps chromium
      - name: Run Playwright tests
        run: pnpm test:playwright
      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # ratchet:actions/upload-artifact@v7.0.1
        with:
          name: playwright-rapport
          path: playwright/rapport
          retention-days: 7
