name: Pull request
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: Pull request
    permissions:
      contents: read
    uses: navikt/familie-baks-gha-workflows/.github/workflows/pull-request-yarn.yaml@main # ratchet:exclude
    with:
      node-version: '24'
      skip-cypress: false
    secrets: inherit