name: Scan vulnerabilities
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' # monday 06:00
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.github/**.yaml'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
jobs:
  scan-vulnerabilities:
    name: Scan vulnerabilities
    permissions:
      contents: write # to write sarif
      security-events: write # push sarif to github security
    uses: navikt/familie-baks-gha-workflows/.github/workflows/scan-vulnerabilities-yarn.yaml@95b1f0f855f8c73015db7b815d249ee11f035906 # ratchet:navikt/familie-baks-gha-workflows/.github/workflows/scan-vulnerabilities-yarn.yaml@main
    secrets: inherit
