apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-sak-frontend-redis
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    "nais.io/run-as-group": "0"
    "nais.io/read-only-file-system": "false"
spec:
  image: bitnami/redis:6.0.16
  port: 6379
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1
  envFrom:
    - secret: familie-ba-sak-frontend-redis
  resources: # you need to monitor need your self
    limits:
      cpu: 250m 
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    port: 6379
    protocol: redis